version: "1"
services:
  frontend:
    image: frontend-react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "bonbot-frontend"
    volumes:
      - ./frontend/src:/frontend/src # for watching files
    networks:
      - app-network
    ports:
      - "4000:80"
    env_file:
      - ./frontend/.env
  backend:
    image: backend-fastapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "bonbot-backend"
    volumes:
      - ./backend:/app # for watching files
    networks:
      - app-network
    env_file:
      - ./backend/.env
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
